blueprint:
  name: Nordpool cheap hours (Aangepast)
  description: >
    Deze blueprint gebruikt de nordpool integratie en laat je kiezen hoeveel uren
    je als goedkoop wilt definiëren, en maakt automatiseringen op basis van die informatie.
    Je kunt nu ook een tijdsbestek opgeven waarbinnen naar goedkope uren wordt gezocht.
  domain: automation
  source_url: https://github.com/kullarkert/ha_nordpool_hours_blueprint/blob/main/nordpool_cheap_prices.yaml
  input:
    grid_area:
      name: Grid area sensor
      description: Dit is je grid area sensor
      selector:
        entity:
          domain:
            - sensor
          integration: nordpool
          multiple: false
    cheap_hours:
      name: Goedkope uren
      description: Aantal goedkope uren
      default: 5
      selector:
        number:
          min: 0.0
          max: 24.0
          mode: slider
          step: 1.0
          unit_of_measurement: "h"
    start_time:
      name: Starttijd
      description: "Tijd waarop de zoekperiode voor goedkope uren begint"
      default: "00:00:00"
      selector:
        time: {}
    end_time:
      name: Eindtijd
      description: "Tijd waarop de zoekperiode voor goedkope uren eindigt"
      default: "23:59:59"
      selector:
        time: {}
    day_monday:
      name: Uitvoeren op maandag
      description: Voer de actie uit op maandag
      default: true
      selector:
        boolean:
    day_tuesday:
      name: Uitvoeren op dinsdag
      description: Voer de actie uit op dinsdag
      default: true
      selector:
        boolean:
    day_wednesday:
      name: Uitvoeren op woensdag
      description: Voer de actie uit op woensdag
      default: true
      selector:
        boolean:
    day_thursday:
      name: Uitvoeren op donderdag
      description: Voer de actie uit op donderdag
      default: true
      selector:
        boolean:
    day_friday:
      name: Uitvoeren op vrijdag
      description: Voer de actie uit op vrijdag
      default: true
      selector:
        boolean:
    day_saturday:
      name: Uitvoeren op zaterdag
      description: Voer de actie uit op zaterdag
      default: true
      selector:
        boolean:
    day_sunday:
      name: Uitvoeren op zondag
      description: Voer de actie uit op zondag
      default: true
      selector:
        boolean:
    expensive:
      name: Duur
      description: Actie uit te voeren tijdens dure uren
      default: []
      selector:
        action: {}
    cheap:
      name: Goedkoop
      description: Actie uit te voeren tijdens goedkope uren
      default: []
      selector:
        action: {}
variables:
  grid_area_var: !input grid_area
  cheap_hours_var: !input cheap_hours
  start_time: !input start_time
  end_time: !input end_time
  day_monday: !input day_monday
  day_tuesday: !input day_tuesday
  day_wednesday: !input day_wednesday
  day_thursday: !input day_thursday
  day_friday: !input day_friday
  day_saturday: !input day_saturday
  day_sunday: !input day_sunday
trigger:
  - platform: state
    entity_id: !input grid_area
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {%- set today = now().weekday() -%}
              {%- set current_time = now().strftime("%H:%M:%S") -%}
              {%- if (today == 0 and day_monday) or (today == 1 and day_tuesday) or (today == 2 and day_wednesday) or (today == 3 and day_thursday) or (today == 4 and day_friday) or (today == 5 and day_saturday) or (today == 6 and day_sunday) -%}
                {%- if start_time <= current_time <= end_time -%}
                  {%- set filtered_prices = state_attr(grid_area_var, 'today') | selectattr('hour', 'ge', start_time.split(':')[0] | int) | selectattr('hour', 'le', end_time.split(':')[0] | int) | list -%}
                  {{ state_attr(grid_area_var, 'current_price') | float < (filtered_prices | sort(attribute='value'))[ cheap_hours_var | int ].value }}
                {%- else -%}
                  {{ false }}
                {%- endif -%}
              {%- else -%}
                {{ false }}
              {%- endif -%}
        sequence: !input cheap
      - conditions:
          - condition: template
            value_template: >
              {%- set today = now().weekday() -%}
              {%- set current_time = now().strftime("%H:%M:%S") -%}
              {%- if (today == 0 and day_monday) or (today == 1 and day_tuesday) or (today == 2 and day_wednesday) or (today == 3 and day_thursday) or (today == 4 and day_friday) or (today == 5 and day_saturday) or (today == 6 and day_sunday) -%}
                {%- if start_time <= current_time <= end_time -%}
                  {%- set filtered_prices = state_attr(grid_area_var, 'today') | selectattr('hour', 'ge', start_time.split(':')[0] | int) | selectattr('hour', 'le', end_time.split(':')[0] | int) | list -%}
                  {{ state_attr(grid_area_var, 'current_price') | float > (filtered_prices | sort(attribute='value'))[ cheap_hours_var | int ].value }}
                {%- else -%}
                  {{ false }}
                {%- endif -%}
              {%- else -%}
                {{ false }}
              {%- endif -%}
        sequence: !input expensive
    default: []
